# there is no ci
#
FROM ikeikeikeike/lit:built as noci
WORKDIR /workspace/lit
ENV RAILS_ENV=production

COPY ./ ./

RUN cp -pR /built/lit/vendor/bundle /workspace/lit/vendor/ \
 && cp -pR /built/lit/node_modules /workspace/lit/
RUN yarn install \
          && \
    bundle install --path vendor/bundle --jobs=2 --without development && hash -r \
          && \
    bundle exec rake assets:precompile

# main

FROM ikeikeikeike/docker-ruby:2.5.1-pg
WORKDIR /apps/lit
ENV RAILS_ENV=production

COPY --from=noci /workspace/lit /apps/lit

RUN yarn install \
          && \
    bundle install --path vendor/bundle --jobs=2 --without development && hash -r \
          && \
    bundle exec rake assets:precompile

# EXPOSE 3000
# ENTRYPOINT
