FROM ikeikeikeike/ruby:2.5.1

WORKDIR /apps/lit

ENV RAILS_ENV=production

ADD lit.tar.gz ./
WORKDIR lit

RUN yarn install \
          && \
    bundle install --path vendor/bundle --jobs=2 --without development && hash -r \
          && \
    bundle exec rake assets:precompile

# EXPOSE 3000
# ENTRYPOINT
